### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by FranklinChen** [centeropenmiddleware/XSDInferencer#2]
I ran `mvn package` and got an error:

```console
Running es.upm.dit.xsdinferencer.tests.generation.generatorimpl.ResultsGeneratorImplTest
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.14 sec <<< FAILURE!
testNormal(es.upm.dit.xsdinferencer.tests.generation.generatorimpl.ResultsGeneratorImplTest)  Time elapsed: 0.005 sec  <<< FAILURE!
]rg.junit.ComparisonFailure: expected:<...fault="qualified" />[
<!-- I am testing -...> but was:<...fault="qualified" />[]
<!-- I am testing -...>
	at org.junit.Assert.assertEquals(Assert.java:115)
...
```

**Comment by palonsoro** [comment]
Ok. This is because of a mistake on a unit test. I hardcoded a CRLF in one test string instead of getting the OS-specific line end character(s) as I did at the rest of the tests. Please give me a minute to fix it.

**Comment by palonsoro** [comment]
I am not currently working here now, so I cannot push directly the changes. I have just made a pull request with the minor changes from a fork at my personal account.

**Comment by alvnav** [comment]
I just merged the change to the master branch.
